# Generated by Django 4.1.3 on 2022-12-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsstory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='story_image',
            field=models.ImageField(null='true', upload_to='image/s'),
            preserve_default='true',
        ),
    ]
