# Generated by Django 4.1.3 on 2022-12-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_story_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='story_image',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
