# Generated by Django 4.1.3 on 2022-12-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_comment_content_editstory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditStory',
        ),
    ]
