# Generated by Django 4.1.3 on 2022-12-31 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0010_alter_newsstory_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='disliked_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
