# Generated by Django 4.1.3 on 2023-01-01 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0013_alter_newsstory_disliked_by_alter_newsstory_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='loved_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='loved_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
